### ISSUE TITLE
Index structure, Magneto statics and References

### ISSUE THREAD

**Issue by joha2** [hplgit/fenics-tutorial#18]
First of all, thank you for writing Fenics and the documentation for it. It's a great tool and it has a very good documentation! Despite that I have a few comments/questions on the tutorial:

* Index structure: For me as a physicist it's very difficult to read the equations which contain tensors and vectors due to this minimal context formulas. Would it be possible to write them in an index notation like in special or general relativity? (I.e. vector A -> A_i, second rank tensor sigma -> \sigma_{ij} or nabla u + (nabla u)^T -> \partial_i u_j + \partial_j u_i). IMHO this would have several advantages for clarity and clarification. (I would also help in translation if necessary.)
* In the magneto statics section I did not really understand how you came from the rot rot equation to the grad div-type one (before restricting to two dimensions, eq. (4.20)): For a homogenious medium with mu = const this step is trivial by using the Coulomb gauge, but I think this is not valid here anymore. Could you please explain this step further?
* This brings me to the last point: Besides the list of references at the beginning, could you please give some references for further research in the appropriate subsections? I'm a beginner in FEM methods or special treatment of physical theories in FEM, therefore a few (beginner) references for e.g. the non-standard examples (elasticity theory, magneto statics, navier-stokes) would be very helpful (at least for me ;-)).

Thank you in advance! Best regards, Johannes

**Comment by alogg** [comment]
Thanks for the nice comments.

1. Index notation: No, I don't want to rewrite the book in index notation. The notation we use is the one that maps most naturally to the FEniCS code notation so this is the most appropriate in my opinion.

2. Getting from the rot-rot: Good point. I worked this out using pen and paper (I think...) but didn't want to spell out the details. I agree it would be good to add those details. Please register this as an issue and so that I (or someone else) will remember to fix it.

3. References: I know of a good reference for the Navier-Stokes case but not for the other two examples. Please register also this as an issue and I will add the reference later.

Thanks!

**Comment by alogg** [comment]
So I'm closing down this issue, but please register two new issues for item (2) and (3).

**Comment by joha2** [comment]
Thank you for your immediate answer! For (1) I totally understand your point, but in the current notation it's really difficult to work out the details for myself (in particular for (4.20)). Is it still possible to add the index notation as footnote at points where the other one seems missleading? For (2) and (3) I will register two new issues.

**Comment by alogg** [comment]
Yes, a footnote can definitely be added. Please mark the equations that are
of particular importance (but not too many...)

ons 7 dec. 2016 kl 23:21 skrev joha2 <notifications@github.com>:
